[NX-19] Adds image_transformaion suggesting in products endpoints
spree/spree-storefront-api-v2-js-sdk pull request #255
Opened 2021-09-23 14:23 UTC by aplegatt

2021-09-23 18:36 UTC, damianlegawiec requested changes

2021-09-23 18:36 UTC, damianlegawiec commented on src/interfaces/Query.ts
> +    quality?: string
@aplegatt this should be a number

2021-09-23 18:36 UTC, damianlegawiec commented on src/interfaces/Query.ts
> +    size?: number
@aplegatt this on the other hand is a string eg. `100x80`

2021-09-24 13:38 UTC, tniezg approved these changes

2021-09-24 13:38 UTC, merged